apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-external
  namespace: lab05-$STUDENT_NAME
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: db-from-vault
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: prod/database
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/database
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: prod/database
        property: host
