apiVersion: v1
kind: Pod
metadata:
  name: rbac-test
  namespace: lab07-$STUDENT_NAME
spec:
  serviceAccountName: pod-viewer
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["sleep", "3600"]
  restartPolicy: Never
